version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - '13306:3306'
    environment: # -e 옵션
      - MYSQL_DATABASE=moyea_run
      - MYSQL_ROOT_PASSWORD=root
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis
    container_name: redis
    ports:
      - 16379:6379
    restart: on-failure
  main-server:
    container_name: main-server
    build: .
    command: ./entrypoint.dev.sh
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
    environment:
      - PORT=3000
      - NODE_ENV=dev
