apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafkamonitering
  name: kafkamonitering
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    io.kompose.service: kafkamonitering
status:
  loadBalancer: {}
