apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30005
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
