apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: noti-server
  name: noti-server
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30002
  ports:
    - name: '4000'
      port: 4000
      targetPort: 30009
  selector:
    io.kompose.service: noti-server
status:
  loadBalancer: {}
