apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: noti-server
  name: noti-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: noti-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: noti-server
    spec:
      containers:
        - args:
            - ./entrypoint.prod.sh
          envFrom:
            - secretRef:
                name: noti-secrets
          image: dnatuna/moyeorun-noti-server:0.0.2
          name: noti-server
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: '1.5Gi'
              cpu: '1000m'
            limits:
              memory: '1.5Gi'
              cpu: '1000m'
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
