apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: main-server
  name: main-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: main-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: main-server
    spec:
      containers:
        - args:
            - ./entrypoint.prod.sh
          envFrom:
            - secretRef:
                name: server-secrets
          image: dnatuna/moyearun-main-server:0.0.2
          name: main-server
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '1Gi'
              cpu: '1000m'
            limits:
              memory: '2Gi'
              cpu: '1500m'
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

status: {}
