apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: main-server
  name: main-server
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
  selector:
    io.kompose.service: main-server
status:
  loadBalancer: {}
